safe: true
encoding: UTF-8
baseurl: /
url: https://roundcube.net
enforce_ssl: roundcube.net
hostname: "https://roundcube.net"
permalink: news/:year/:month/:day/:title
paginate: 6
paginate_path: news/page:num